version: "3"
services:

  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - 18080:15672
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    restart: on-failure

  nominatim:
    image: nominatim
    command: sh /app/start.sh
    ports:
      - 6432:5432
      - 7070:8080
    volumes:
      - /root/geodata/postgresdata:/var/lib/postgresql/9.5/main

  flatcrawl:
    image: floschnell/flatcrawl:latest
    ports:
      - "8443:8443"
    environment:
      - FLATCRAWL_DATABASE_KEY
      - FLATCRAWL_BOT_TOKEN
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    restart: on-failure
  
  routing-car:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/bayern-latest.osrm
    volumes:
      - /opt/osm/car:/data
    ports:
      - "5000:5000"

  routing-bicycle:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/bayern-latest.osrm
    volumes:
      - /opt/osm/bicycle:/data
    ports:
      - "5001:5000"

  routing-foot:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/bayern-latest.osrm
    volumes:
      - /opt/osm/foot:/data
    ports:
      - "5002:5000"